services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cinevobis_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mariadb:11
    container_name: cinevobis_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cinevobis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=root --password=root ping"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: